site_name: 科研仔技能百科
nav:
    - Home: index.md
    - 操作系统:
        - Windows:  OS/Windows.md
        - Linux:    OS/Linux.md
        - WSL*:     OS/WSL.md
    - StepByStep:   StepByStep.md
    - 文本编辑: 
        - VS Code:   TextEdit/VSCode.md
        - Markdown: TextEdit/Markdown.md
        - Latex:    TextEdit/Latex.md
        - Nano*:    TextEdit/Nano.md
        - Vim*:     TextEdit/Vim.md
        - sed*:     TextEdit/sed.md
    - 编程语言:
        - Shell:     Shell/Shell.md
        - Python:
            - 入门: Python/Python.md
            - 菜鸟笔记: Python/tyro_note.md
            - Jupyter Notebook: Python/Jupyter.md
        - C/C++:      cpp.md
        - R: R/R.md
        - Wolfram Mathematica*: Mathematica/README.md
    - 远程连接:
        - SSH:  RemoteConnect/ssh.md
        - RDP(远程Windows桌面)*: RemoteConnect/rdp.md
    - 版本控制:
        - Git:      Git/Git.md
        - GitHub:   Git/GitHub.md
    - 文档/文献:
        - Zeal:     zeal.md
        - Citavi:   Unsorted/Citavi.md
    - 其他*:
        - 网络相关:
            - VPN:  Unsorted/VPN.md
            - 内网穿透: Unsorted/nattunnel.md
        - 数据库:
            - EspressoDB:    Unsorted/EspressoDB.md

repo_url: https://github.com/kyzjnbk/kyzjnbk

theme: # https://squidfunk.github.io/mkdocs-material/getting-started/
    name: material
    language: zh # 中文，解决中文搜索问题

extra:
    version: 0.1

markdown_extensions: # https://python-markdown.github.io/extensions/
    - admonition # https://python-markdown.github.io/extensions/admonition
                 #  attention, caution, danger, error, hint, important, note, tip, and warning;
    - attr_list
    - def_list
    - toc
    - wikilinks:
        base_url: ./
        end_url: .md
    - pymdownx.highlight:
        linenums: true
        linenums_style: pymdownx-inline
        use_pygments: true
        auto_title: false
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.keys
    - pymdownx.arithmatex:
        generic: true



plugins:
    - search
    - git-revision-date-localized # https://github.com/timvink/mkdocs-git-revision-date-localized-plugin
    - mkdocs-video # https://github.com/soulless-viewer/mkdocs-video


