site_name: 科研仔技能百科
nav:
    - Home: README.md
    - StepByStep: StepByStep.md
    - 文本编辑: 
        - VSCode:   TextEdit/VSCode.md
        - Markdown: TextEdit/Markdown.md
        - Latex:    TextEdit/Latex.md
        - Nano*:     TextEdit/Nano.md
        - Vim*:      TextEdit/Vim.md
        - sed*:      TextEdit/sed.md
    - 环境配置:
        - Linux:    Unsorted/Linux.md
        - WSL:      Unsorted/WSL.md      
        - 远程连接:
            - SSH:  RemoteConnect/ssh.md
            - rdp*:  RemoteConnect/rdp.md
    - 编程语言:
        - Python:
            - 入门: Python/Python.md
            - 菜鸟笔记: Python/tyro_note.md
            - Jupyter Notebook: Unsorted/Jupyter Notebook.md
        - Shell:     Shell/Shell.md
        - C++*:      Cpp/Cpp.md
        - Wolfram Mathematica*: Mathematica/README.md
    - 版本控制:
        - Git:      VersionControl/git.md
        - GitHub:   Unsorted/GitHub.md
    - 文档/文献:
        - Zeal:     Unsorted/Zeal.md
        - Citavi:   Unsorted/Citavi.md
    - 其他*:
        - 网络相关:
            - VPN:      Unsorted/VPN.md
            - 内网穿透:     Unsorted/nattunnel.md
        - 数据库:
            - EspressoDB:    Unsorted/EspressoDB.md
repo_url: https://github.com/tanganke/kyzjnbk
theme: windmill

